opentofu_pw: ENC[AES256_GCM,data:etm6dBltNCTRDeXyZQvRMy/GH3Q=,iv:4zxNkOTFqSrpJQsqYIFj47PzlJdR35fBm5pjjQTx1aU=,tag:NEDdPaVPQCfIuy/jBf8ZTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWGttMEFOQU1xN2xDMWk5
            TEZONXB0T1ZrMmc1WmtiaS8zYWVBamNtdURFCkM5bG00aDZYSURadFZLWWN1U2hX
            R2RWTXdCZlVFYXFuOG1Ybzg4Y25hSFEKLS0tIDVidVFEU012QUVQYVRRak9acnRt
            eS9PRTlYZDBhOHJNT0EvV0VsR0poOG8KW2zDfWcOmycUo3W9LyVv0UgA7ZNDzZE+
            URwh+n15NPc41IPcZFmS2c5SPJNk2pqU2vUFdMAyw9TbuSj8reRF0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-15T21:31:31Z"
    mac: ENC[AES256_GCM,data:1NEOwQrUqouN3ktbTjF9nwOqb0Ge/cFvp3oRbHWQLZ4Y+Qd7yVJgGPX4BAJmsrZVQXuxPOCX5wj+BD/xUyFRemrm4fOyHYG0KgeNHHnB3oaARWH96fPC6EkvgzUnqqM//g/+X38Fm4obxMzN3AE4LHsXuhb0gSVPuA0EkK3jlDA=,iv:6lakoOAGoSEmPaBgyP7moPJ6oItHlhZJzVjLu7hMziM=,tag:yabs59m1lsXthnoIK8XaPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
