name: Deploy tgtg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: python3 -m pip install -r requirements.txt && python3 build.py
