name: Deploy VILF
on:
  push:
    branches: develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install -r requirements.txt
      - run: ./vilf build
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.VILF_CREDS }}"
      - uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -R build gs://vilf-org
