name: Deploy VILF
on:
  push:
    branches: develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: "1"
      UV_NO_DEV: "1"
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - run: uv python install

      - run: uv sync

      - run: ./vilf build

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.VILF_CREDS }}"

      - uses: google-github-actions/setup-gcloud@v0

      - run: gsutil -m rsync -R build gs://vilf-org
